<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Programmes Offered</name>
   <tag></tag>
   <elementGuidId>638bd078-9517-4796-8049-73333383048e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='hero']/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn-get-started.scrollto.animated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Programmes Offered&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9a93d6bf-1b26-48e2-a4e2-5145fc581b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>files/Programmes_Offered.pdf</value>
      <webElementGuid>fc4ac469-f3c1-4993-ba5e-53d0d13f5e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8a873137-69e3-4877-8b0e-6757f57d957d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-get-started scrollto animated</value>
      <webElementGuid>97f989f0-8d61-46ca-a751-4244a1ee8737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Programmes Offered</value>
      <webElementGuid>aaf8a7cb-e2ec-414a-a29a-c03acff3cec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hero&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 order-1 order-lg-2 hero-img&quot;]/a[@class=&quot;btn-get-started scrollto animated&quot;]</value>
      <webElementGuid>df6c4efb-1a88-4cb2-9c05-a038ca4ffb57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='hero']/div/div/div[2]/a</value>
      <webElementGuid>12cdca71-37f7-4cfc-ad2f-5d3f00251714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Programmes Offered')]</value>
      <webElementGuid>78660947-0ea0-4064-884a-ad973d5bcd50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicant Login'])[2]/following::a[1]</value>
      <webElementGuid>4c121a88-9111-4ca6-b34d-ace7cb6deb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicant Register'])[2]/following::a[2]</value>
      <webElementGuid>d7e6a496-098d-4e6c-994a-3ef2d2a9b4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fee Structure'])[1]/preceding::a[1]</value>
      <webElementGuid>82e45e98-3f24-4840-a34b-38c161a48969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Fee Payment Procedure'])[1]/preceding::a[2]</value>
      <webElementGuid>d7afe355-d0c6-4cc9-8a9c-00d17956c95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Programmes Offered']/parent::*</value>
      <webElementGuid>57e792aa-3ec1-4eff-86d2-85e89ca3cddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'files/Programmes_Offered.pdf')]</value>
      <webElementGuid>363dfde1-6516-4c85-bac7-eaed3e1e767d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>232cdeb1-18e8-4f71-a6bd-261d04c8492e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'files/Programmes_Offered.pdf' and (text() = 'Programmes Offered' or . = 'Programmes Offered')]</value>
      <webElementGuid>c07f2ae5-a6ac-486e-8094-176261382bf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
