<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_AudioCaptcha_loadIcon</name>
   <tag></tag>
   <elementGuidId>603a811f-1d28-4baf-9de4-b920c78580c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='imgselcaptcha']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.loadIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Refresh&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>49e03838-dd9a-4840-9ab6-5b96fdfc923b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loadIcon</value>
      <webElementGuid>f417f712-dacd-4950-8b3a-2079f3e760b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgselcaptcha&quot;)/a[1]/i[@class=&quot;loadIcon&quot;]</value>
      <webElementGuid>7bf4dd99-033c-474d-9173-d44ca4c943bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='imgselcaptcha']/a/i</value>
      <webElementGuid>d6f3867f-f1c0-4446-ac10-dee0ffb6538e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>ea9a1a26-9be4-4dae-bf15-32ef1f9f42bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
