<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Industry_select_category_icons</name>
   <tag></tag>
   <elementGuidId>fe57b517-bcc9-4354-bd8a-8c894134c797</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='institutetypeform']/div/div/div[10]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Other Institutions&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2db9f0f3-7c33-49c4-90c3-3c3fa87de697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_category_icons</value>
      <webElementGuid>d17ffdfa-6de9-44f0-9285-2ff62a0105e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/sbijava/sbcollectrevamp/images/svg/temple.svg</value>
      <webElementGuid>f4517409-5f32-482e-a1b0-405f9a27c682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;institutetypeform&quot;)/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-6&quot;]/a[@class=&quot;TextStyle&quot;]/img[@class=&quot;select_category_icons&quot;]</value>
      <webElementGuid>d5d06656-ae18-4c4d-a939-6e61162989d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='institutetypeform']/div/div/div[10]/a/img</value>
      <webElementGuid>d8a3cfe3-a0b0-4e39-9a7b-b141e73aeaf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/a/img</value>
      <webElementGuid>5ba91387-3f1f-4257-8695-9acd451ad42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/sbijava/sbcollectrevamp/images/svg/temple.svg']</value>
      <webElementGuid>41783833-41a7-4663-8954-c0ac44b32a20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
