<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mobileNo</name>
   <tag></tag>
   <elementGuidId>9ecd98a1-c0f8-486b-bde3-d2c10d84f037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobileNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mobileNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mobileNo</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ec83262-30f3-4dde-8bcc-cbe0fa09297e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobileNo</value>
      <webElementGuid>a8beb35c-09ab-4910-946e-5c678dc8d1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobileNo</value>
      <webElementGuid>01295ff4-42f6-485d-97de-57feb16c450d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]{10}</value>
      <webElementGuid>4cd9651d-1ab7-4ff1-8ab5-db9868ef8807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>You can enter only 10 digits...</value>
      <webElementGuid>c31a30d3-05a4-4a57-9b9b-19d112bd2e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3baa773-3d47-4b3c-afd6-0d3f20a72d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ba10022e-a6e3-4e46-ab5f-5742d3fb7f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Number</value>
      <webElementGuid>b0b0a835-b774-45bb-9e00-d3f2989ef97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9516daeb-3cf9-46f0-9ac0-0b781e266a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncopy</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>e7c97e0f-1a06-4f05-adfe-2f7729e38b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>19e2bbcd-1dbe-481b-bd46-042d6ac4e142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncut</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>5129ddff-ef00-4e2e-b25e-cc1d3a16429d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobileNo&quot;)</value>
      <webElementGuid>99b962c2-fcba-4745-9f5b-36b74228a134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mobileNo']</value>
      <webElementGuid>046d1d1e-859a-4084-af59-85049c6b06b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ForIndividual']/div[2]/div/div[2]/input</value>
      <webElementGuid>8d8f214c-6318-4313-a17c-40b73ebb73a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>1f521b94-439c-45a2-b5e0-3c3403eef6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'mobileNo' and @id = 'mobileNo' and @title = 'You can enter only 10 digits...' and @type = 'text']</value>
      <webElementGuid>a83cb215-e32b-4e25-b11b-d668e4a82ce5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
