<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ADDRESS LINE1_outref14</name>
   <tag></tag>
   <elementGuidId>fff42c49-9b75-4ea2-974b-f865922b506e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='outref14']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#outref14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#outref14</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fe1d7d3-a39b-4d3c-9ee2-4ce1a44ab751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e6d1911d-bfc4-419a-b416-29f8d21694a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncopy</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>e85a7ac9-c369-4f83-9809-f34a4830f970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>36c94b4a-b68e-472d-bfdb-3fb9948bbac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncut</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>739cb839-d71c-4378-8e97-66a16983c388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>23c5b6a7-995b-49f6-a755-5bf32a782312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>outref14</value>
      <webElementGuid>4908e76a-4947-492f-b080-5c385604f901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outref14</value>
      <webElementGuid>7ffa7de4-dcfc-47be-86ea-21784c61f94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outref14&quot;)</value>
      <webElementGuid>ab98fdab-1810-4f93-b411-8d841ecfcbd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='outref14']</value>
      <webElementGuid>e915d2f8-214d-4be3-898d-6f2ea38a02ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/input</value>
      <webElementGuid>5e8f9135-a63b-4236-bba2-0f2d84f3d93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'Text' and @name = 'outref14' and @id = 'outref14']</value>
      <webElementGuid>56aa385c-5ee4-45c5-af89-58c597304d01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
