<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CONTACT NO_outref20</name>
   <tag></tag>
   <elementGuidId>503eeb1e-4a0c-4ce7-9116-45ea85c1315d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='outref20']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#outref20</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#outref20</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bb58fa9-9067-4829-8bf9-920a4272df8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>664a17bd-3951-4a21-8aa0-6c80a7f2b9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncopy</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>d83405d7-e766-4019-9ed2-e24dfa961b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>1212c08e-777d-4803-8d0b-2b7e74585083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncut</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>f1de906e-9b0e-4f0b-abd6-ae28691b26d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>a80e1015-58c8-4500-8931-02d3cde768f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>outref20</value>
      <webElementGuid>efd277f3-ade9-4072-b8ef-2b9390914065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outref20</value>
      <webElementGuid>757afcd8-d815-4b6d-a52a-2a8264dd1679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outref20&quot;)</value>
      <webElementGuid>c24e4ca2-240d-4635-8b95-b5b0e25e9514</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='outref20']</value>
      <webElementGuid>ac31ebed-9f58-4ee1-ab35-ce3243037ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[2]/input</value>
      <webElementGuid>78000f9c-b9dd-4e0f-9571-e134b1b1164e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'Text' and @name = 'outref20' and @id = 'outref20']</value>
      <webElementGuid>b0bbaf86-7425-4d26-8f32-411ed99809ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
