<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_--Select ROOM TYPE AC--</name>
   <tag></tag>
   <elementGuidId>98a06ac2-2c76-44de-8732-d39cf2ed6120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-outref24-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-outref24-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;--Select ROOM TYPE AC--&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>14c70b20-a3f2-493d-8628-eb23d5b846e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>edb05376-8ab2-4643-813e-c3d0d08fc536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-outref24-container</value>
      <webElementGuid>ed1988a8-c8a9-4077-aeba-0171c44afde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>d2a482a9-44c4-4824-b881-f3eb83fce415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f025b63e-2550-4ba8-9d6f-9f72749f3df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>--Select ROOM TYPE AC--</value>
      <webElementGuid>7e6d255b-960e-4b3a-a0cd-d383ccbc4893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select ROOM TYPE AC--</value>
      <webElementGuid>451125e3-d75a-4453-bda2-12fc1477d2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-outref24-container&quot;)</value>
      <webElementGuid>cdc8ff08-a570-456d-b20a-612a5ed4636a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-outref24-container']</value>
      <webElementGuid>b59c3ca2-56b5-40b9-8b49-cbeecaed54c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROOM TYPE AC *'])[1]/following::span[5]</value>
      <webElementGuid>65998f19-78ce-4f14-a953-460d264e4f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHECK OUT DATE *'])[1]/following::span[5]</value>
      <webElementGuid>a6b87478-3b42-4ef5-9a17-da23b3406876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO OF PERSONS *'])[1]/preceding::span[3]</value>
      <webElementGuid>585a9c68-6d35-4149-aae8-c9b5eee0a13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount *'])[1]/preceding::span[3]</value>
      <webElementGuid>5f36e610-4060-4ef7-8770-06639d5a8550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/span</value>
      <webElementGuid>76a50fae-71cd-42bf-875a-ec5fd42749f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-outref24-container' and @title = '--Select ROOM TYPE AC--' and (text() = '--Select ROOM TYPE AC--' or . = '--Select ROOM TYPE AC--')]</value>
      <webElementGuid>24b1ed90-ce49-40ab-849b-45b8d3f40cb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
