<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Admissions open for Academic Year 2024_fa_5b5255</name>
   <tag></tag>
   <elementGuidId>9a1c8fd7-6be9-4c72-99bc-67b3ec4cc438</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section/div[2]/div/div/div[3]/div/div/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-scroll</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section >> internal:has-text=&quot;Admissions open for Academic Year 2024 Apply Now! Application Link Programmes Of&quot;i >> i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b58ec381-3076-4ac3-81c5-7350d52b8766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-scroll</value>
      <webElementGuid>9da31343-0e3d-4575-a59c-ef7b1c74e6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>015a4b56-685e-4bb4-99bf-fdfa2d049993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;content-section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8  position-relative z_2&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3&quot;]/div[@class=&quot;icon_box_only trans type_one type_two&quot;]/div[@class=&quot;icon_box_in trans&quot;]/div[@class=&quot;icon&quot;]/i[@class=&quot;fa-solid fa-scroll&quot;]</value>
      <webElementGuid>49ecde4a-adad-4309-b644-0ec06a1978db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/div[2]/div/div/div[3]/div/div/div/div/i</value>
      <webElementGuid>db85f44a-a013-4100-92eb-c60291ba07ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/i</value>
      <webElementGuid>ac970280-177e-4dd6-bc8e-52d77fae57d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
