<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , wacframe, , ))_wacframe</name>
   <tag></tag>
   <elementGuidId>edb50cd7-d74f-4354-86ad-e72f6d586581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='wacframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wacframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;wacframe&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e437746a-dd1a-46c1-9e74-936a0a546f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d065106a-2074-417b-b970-e639ecc7da0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wacframe</value>
      <webElementGuid>19468fc3-5cbe-446e-9887-292d96a87b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wacframe</value>
      <webElementGuid>b2c563fc-5b7c-413f-8134-5a31c8cbf771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Office on the web Frame</value>
      <webElementGuid>32878cd3-3078-42b5-858c-387b11601cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3da56853-09c4-4039-bc31-2bec00511e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wacframe&quot;)</value>
      <webElementGuid>199ee1e3-cc5c-464c-b93b-b5a2497ebcd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Mother Teresa/Page_MTWU_Files/iframe_Ph.D. Entrance Examination online Fe_4dc069</value>
      <webElementGuid>bb6c7d73-28de-4454-90f9-3168422f35b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='wacframe']</value>
      <webElementGuid>654294f5-b23a-4859-964a-b21cc5ee99bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>45f22c96-9606-4dba-91e3-9065f1e072c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'wacframe' and @name = 'wacframe' and @title = 'Office on the web Frame']</value>
      <webElementGuid>d2b8d0e1-7850-407b-a63e-2a6febbaca0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
